/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.chitietspdao;
import dao.lichsudangnhapdao;
import dao.nguyenlieudao;
import dao.sqlserverprovider;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.chitietsp;
import pojo.nguyenlieu;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author HuuDuc
 */
public class jframeqlthanhpham extends javax.swing.JFrame {
String tennl="";
String manl="";
    /**
     * Creates new form jframeqlquytrinh
     */
    public jframeqlthanhpham() {
        this.setTitle("Form QUẢN LÝ THÀNH PHẨM");
        initComponents();
      
        adddatacombobox();
        Hienthi();
        demsosanpham();
        demsonguyenlieu();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtb1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb2 = new javax.swing.JTable();
        lb1 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        lb2 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        txtdang = new javax.swing.JTextField();
        txtnhietdo = new javax.swing.JTextField();
        panelfoot = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnaddnl = new javax.swing.JButton();
        btnupdatenl = new javax.swing.JButton();
        btnxoanl = new javax.swing.JButton();
        btnthemsp = new javax.swing.JButton();
        btnchuyendoi = new javax.swing.JButton();
        btnxoasp = new javax.swing.JButton();
        btntimkiem = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jcb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtsumsp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsumnl = new javax.swing.JTextField();
        panelhead = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jmenuaccout = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nguyên liệu", "Tên nguyên liệu", "Dạng vật lý", "Nhiệt độ "
            }
        ));
        jtb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb1);

        jtb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã NL", "Mã Loại Sp", "Tên Sản phẩm", "Ngày sản xuất"
            }
        ));
        jScrollPane2.setViewportView(jtb2);

        lb1.setText("Mã nguyên liệu :");

        lb2.setText("Tên nguyên liêu");

        lb3.setText("Dạng vật lý :");

        lb4.setText("Nhiệt độ :");

        panelfoot.setBackground(new java.awt.Color(255, 153, 204));
        panelfoot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setText("Quay lại");

        btnaddnl.setBackground(new java.awt.Color(255, 153, 51));
        btnaddnl.setText("Thêm NL");
        btnaddnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnlActionPerformed(evt);
            }
        });

        btnupdatenl.setBackground(new java.awt.Color(255, 153, 51));
        btnupdatenl.setText("Cập nhật NL");
        btnupdatenl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatenlActionPerformed(evt);
            }
        });

        btnxoanl.setBackground(new java.awt.Color(255, 153, 51));
        btnxoanl.setText("Xóa NL");
        btnxoanl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoanlActionPerformed(evt);
            }
        });

        btnthemsp.setBackground(new java.awt.Color(255, 102, 51));
        btnthemsp.setText("Thêm SP");
        btnthemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemspActionPerformed(evt);
            }
        });

        btnchuyendoi.setBackground(new java.awt.Color(255, 153, 51));
        btnchuyendoi.setText("Chuyển CTSP");
        btnchuyendoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuyendoiActionPerformed(evt);
            }
        });

        btnxoasp.setBackground(new java.awt.Color(255, 153, 0));
        btnxoasp.setText("Xóa SP");
        btnxoasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaspActionPerformed(evt);
            }
        });

        btntimkiem.setBackground(new java.awt.Color(0, 255, 204));
        btntimkiem.setText("Tìm kiếm bằng tên Nguyên liệu");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 255, 0));
        jButton9.setText("Thoát");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(0, 255, 204));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        jcb.setBackground(new java.awt.Color(51, 255, 0));
        jcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nguyên liệu và sản phẩm" }));
        jcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BẢNG CHỨC NĂNG");

        javax.swing.GroupLayout panelfootLayout = new javax.swing.GroupLayout(panelfoot);
        panelfoot.setLayout(panelfootLayout);
        panelfootLayout.setHorizontalGroup(
            panelfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelfootLayout.createSequentialGroup()
                        .addComponent(btnthemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnchuyendoi))
                    .addComponent(jcb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelfootLayout.createSequentialGroup()
                        .addComponent(btnxoasp, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnupdatenl, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btntimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(panelfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfootLayout.createSequentialGroup()
                        .addComponent(btnaddnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoanl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelfootLayout.setVerticalGroup(
            panelfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnchuyendoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoasp)
                    .addGroup(panelfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnupdatenl)
                        .addComponent(btnaddnl)
                        .addComponent(btnxoanl)
                        .addComponent(btnthemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb)
                    .addComponent(btntimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelfootLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnaddnl, btnchuyendoi, btnthemsp, btnupdatenl, btnxoanl, btnxoasp});

        jLabel5.setText("Tổng sản phẩm ");

        jLabel6.setText("Tổng nguyên liệu :");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/unnamed.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/unnamed.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/pngtree-employee-icon-vector-illustration-in-glyph-style-for-any-purpose-png-image_998315.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/pngtree-vector-candy-icon-png-image_4159682.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelheadLayout = new javax.swing.GroupLayout(panelhead);
        panelhead.setLayout(panelheadLayout);
        panelheadLayout.setHorizontalGroup(
            panelheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelheadLayout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelheadLayout.setVerticalGroup(
            panelheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheadLayout.createSequentialGroup()
                .addGroup(panelheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/16225630-print-icon.jpg"))); // NOI18N
        jMenuItem4.setText("In ra");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Đổi màu Theme");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/unnamed (1).png"))); // NOI18N
        jMenuItem1.setText("Màu đỏ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/c.jpg"))); // NOI18N
        jMenuItem2.setText("Màu cam");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/1200px-Button_Icon_Blue.svg.png"))); // NOI18N
        jMenuItem3.setText("Màu xanh");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem7.setText("Mặc định");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jmenuaccout.setText("Tài khoản");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/free-settings-icon-3110-thumb.png"))); // NOI18N
        jMenuItem5.setText("Thiết lập");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmenuaccout.add(jMenuItem5);

        jRadioButtonMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonMenuItem2.setForeground(new java.awt.Color(255, 51, 51));
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Đăng xuất");
        jRadioButtonMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/41566967-logout-button.jpg"))); // NOI18N
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jmenuaccout.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jmenuaccout);

        jMenu5.setText("Setting");

        jMenuItem6.setText("Form giữa màn hình");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Exit");

        jRadioButtonMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Exit");
        jRadioButtonMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/32210569-exit-icon.jpg"))); // NOI18N
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelfoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsumsp)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtsumnl, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addComponent(lb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtten, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addComponent(txtma)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtnhietdo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtdang))))))
            .addComponent(panelhead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelhead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb1)
                            .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnhietdo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsumsp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsumnl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(panelfoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lb1, lb2, lb3, lb4, txtdang, txtma, txtnhietdo, txtten});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb1MouseClicked
        // TODO add your handling code here:
        int row=jtb1.getSelectedRow();
        txtma.setText(String.valueOf(jtb1.getValueAt(row, 0)));
        txtten.setText(String.valueOf(jtb1.getValueAt(row, 1)));
        txtdang.setText(String.valueOf(jtb1.getValueAt(row, 2)));
        txtnhietdo.setText(String.valueOf(jtb1.getValueAt(row, 3)));
    }//GEN-LAST:event_jtb1MouseClicked
private boolean checktrung()
{       int ketqua=0;boolean kq=false;
        String maofnl=txtma.getText();
        ResultSet rs = null;
        sqlserverprovider provin =new sqlserverprovider();
        provin.open();
        String sql="Select count(*) from nguyenlieu where manl='"+maofnl+"'";
        rs=provin.executeQuery(sql);
    try {
        while(rs.next())
        {
            ketqua=rs.getInt(1);
        }
        if (ketqua>0) {
            kq=true;
        }
    } catch (SQLException ex) {
        Logger.getLogger(jframeqlthanhpham.class.getName()).log(Level.SEVERE, null, ex);
    }
    provin.close();
    return kq;
}
    private void btnaddnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnlActionPerformed
        // TODO add your handling code here:
        
           nguyenlieu sh=new nguyenlieu();
        
        boolean error=false;
        if(txtma.getText().isEmpty()==true || txtten.getText().isEmpty()==true||txtnhietdo.getText().isEmpty()==true || txtdang.getText().isEmpty()==true)
        {
            error=true;
//            redtxt(error);
             JOptionPane.showMessageDialog(this,"Không được để trống","Nhắc nhở",JOptionPane.WARNING_MESSAGE);
        }
        else if(checktrung()==true)
        {
             JOptionPane.showMessageDialog(this, "Đã tồn tại mã nguyên liệu vui lòng nhập lại","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            sh.setManl(txtma.getText());
            sh.setTennl(txtten.getText());
            sh.setNhietdo(Integer.parseInt( txtnhietdo.getText()));
            sh.setDangvl(txtdang.getText());
            nguyenlieudao.themsach(sh);
//            redtxt(false);
            Hienthi();
            demsonguyenlieu();
            JOptionPane.showMessageDialog(this, "Thêm nguyên liệu thành công ! ","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnaddnlActionPerformed

    private void btnupdatenlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatenlActionPerformed
        // TODO add your handling code here:
        
          int row =jtb1.getSelectedRow();
       String dang=txtdang.getText();
       float nhietdo=Float.valueOf(txtnhietdo.getText()) ;
       String ma = txtma.getText();
       String ten =txtten.getText();
        if(row==-1)
       {
           JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần cập nhật !","Thông báo",JOptionPane.WARNING_MESSAGE);
       }
        else if(checktrung()==false)
        {
            JOptionPane.showMessageDialog(this, "Mã nguyên liệu không tồn tại vui lòng kiểm tra lại!","Thông báo",JOptionPane.WARNING_MESSAGE);
 
        }
        else
        {
            nguyenlieu sh=new nguyenlieu(ma,ten,nhietdo,dang);        
            nguyenlieudao.capnhatsach(sh);
            Hienthi();
        JOptionPane.showMessageDialog(this, "Cập nhật nguyên liệu thành công ! ","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnupdatenlActionPerformed

    private void btnxoanlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoanlActionPerformed
        // TODO add your handling code here:
              int row=this.jtb1.getSelectedRow();
        
          if (jtb1.getSelectedRow()==-1) 
          {
            JOptionPane.showMessageDialog(this, "Hãy chọn dòng cần xóa");
            return;
          }
            int xoa = JOptionPane.showConfirmDialog(this,
                    "bạn có muốn xóa không","Thông Báo", JOptionPane.YES_NO_OPTION,JOptionPane.YES_OPTION);
              if (xoa==JOptionPane.YES_OPTION) 
            {
                String ma=(String.valueOf(jtb1.getValueAt(row, 0))) ;
                nguyenlieu sh=new nguyenlieu();             
                 sh.setManl(ma);
                 nguyenlieudao.xoasach(sh);
                  JOptionPane.showMessageDialog(this,"xóa thành công","thông báo",JOptionPane.WARNING_MESSAGE);
                   demsonguyenlieu();
                  Hienthi();
            }
              else
              {
                   JOptionPane.showMessageDialog(this,"xóa thất bại","thông báo",JOptionPane.INFORMATION_MESSAGE);
              }
    }//GEN-LAST:event_btnxoanlActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
                int n=JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình !","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (n==JOptionPane.YES_OPTION) {
            lichsudangnhapdao.xoataikhoanfull();
                  JOptionPane.showMessageDialog(this, "Bye bye !!!!!","Chú ý",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
     
        }
        else
            JOptionPane.showMessageDialog(this, "Không thoát","Nhắc nhở",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        trolai(true);
        txtdang.setText("");
        txtma.setText("");
        txtnhietdo.setText("");
        txtten.setText("");
        
    }//GEN-LAST:event_btnresetActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
        tennl=txtten.getText();
        timkiemtheoten();
       
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void jcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbActionPerformed
        // TODO add your handling code here:
        tennl=String.valueOf(jcb.getSelectedItem());
        System.out.println(jcb.getSelectedItem());
         Connection connec=null;
        PreparedStatement pre =null;
        ResultSet rs = null;
        Statement sm=null;
        sqlserverprovider provin =new sqlserverprovider();
        provin.open();
        String sql="Select * from nguyenlieu where tennguyenlieu=N'"+tennl+"'";
        rs=provin.executeQuery(sql);
        try {
            while(rs.next())
            {
                manl=rs.getString("manl");

            }
        } catch (SQLException ex) {
            Logger.getLogger(jframeqlthanhpham.class.getName()).log(Level.SEVERE, null, ex);
        }      
        if(jcb.getSelectedIndex()==0)
        {
            Hienthi();
        }
        else
        {      
            DefaultTableModel dtm=(DefaultTableModel)jtb1.getModel();
            dtm.setRowCount(0);

            for(nguyenlieu sh:nguyenlieudao.timkiemsachtheoma(manl))
            {
                Object datarow[] =new Object[4];
                datarow[0] =sh.getManl();
                datarow[1] =sh.getTennl();
                datarow[2] =sh.getDangvl();
                datarow[3] =sh.getNhietdo();

                dtm.addRow(datarow);         
            }
            
               DefaultTableModel dtm1=(DefaultTableModel)jtb2.getModel();
            dtm1.setRowCount(0);

            for(chitietsp ctsp:chitietspdao.timkiemsachtheoma(manl))
            {
                Object datarow1[] =new Object[4];
                datarow1[0] =ctsp.getManl();
                datarow1[1] =ctsp.getMaloaisp();
                datarow1[2] =ctsp.getTensp();
                datarow1[3] =ctsp.getNgaysx();

                dtm1.addRow(datarow1);         
            }
            
        }  
    }//GEN-LAST:event_jcbActionPerformed

    private void btnthemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemspActionPerformed
        // TODO add your handling code here:
             
        boolean error=false;
        if(txtma.getText().isEmpty()==true || txtten.getText().isEmpty()==true||txtnhietdo.getText().isEmpty()==true || txtdang.getText().isEmpty()==true)
        {
            error=true;
//            redtxt(error);
             JOptionPane.showMessageDialog(this,"Không được để trống","Nhắc nhở",JOptionPane.WARNING_MESSAGE);
        }
           
        else
        {
              String dateString=txtnhietdo.getText();
           SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date(dateString);
        String dateFormat=sdf.format(date);
              
              
            chitietsp  sh=new chitietsp();
            sh.setManl(txtma.getText());
            sh.setTensp(txtten.getText());
            sh.setMaloaisp(txtdang.getText());
            sh.setNgaysx(txtnhietdo.getText());
            chitietspdao.themsp(sh);
            demsosanpham();
            demsonguyenlieu();
            Hienthi();          
            JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công ! ","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnthemspActionPerformed
public boolean chuyendoi(boolean chuyendoi)
{
    boolean chuyen;
    if(chuyen=true)
    {
        lb1.setText("Mã nguyên liệu");
        lb2.setText("Tên sản phẩm");
        lb3.setText("Mã loại SP");
        lb4.setText("Ngày sản xuất");
    }
    return chuyen;
}
//public String ngaysx()
//{
//    String ngay="";
//    ngay=txtnhietdo.getText();
//      SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//        Date date = new Date(ngay);
//        String dateFormat=sdf.format(date);
//        return dateFormat;
//}
public boolean trolai(boolean trolai)
{
    boolean tro;
    if(tro=true)
    {
        lb1.setText("Mã nguyên liệu");
        lb2.setText("Tên nguyên liệu");
        lb3.setText("Dạng vật lý");
        lb4.setText("Nhiệt độ ");
    }
    return tro;
}
    private void btnchuyendoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuyendoiActionPerformed
        // TODO add your handling code here:
        chuyendoi(true);
        
    }//GEN-LAST:event_btnchuyendoiActionPerformed

    private void btnxoaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaspActionPerformed
        // TODO add your handling code here:
             int row=this.jtb2.getSelectedRow();
        
          if (jtb2.getSelectedRow()==-1) 
          {
            JOptionPane.showMessageDialog(this, "Hãy chọn dòng cần xóa");
            return;
          }
            int xoa = JOptionPane.showConfirmDialog(this,
                    "bạn có muốn xóa không","Thông Báo", JOptionPane.YES_NO_OPTION,JOptionPane.YES_OPTION);
              if (xoa==JOptionPane.YES_OPTION) 
            {
                String ma=(String.valueOf(jtb2.getValueAt(row, 0))) ;
                String maloai=(String.valueOf(jtb2.getValueAt(row, 1)));
                chitietsp ctsp =new chitietsp();
                 ctsp.setManl(ma);
                 ctsp.setMaloaisp(maloai);
                 chitietspdao.xoasanpham(ctsp);
                  JOptionPane.showMessageDialog(this,"xóa thành công","thông báo",JOptionPane.WARNING_MESSAGE);
                   demsonguyenlieu();
                   demsosanpham();
                  Hienthi();
                  
            }
              else
              {
                   JOptionPane.showMessageDialog(this,"xóa thất bại","thông báo",JOptionPane.INFORMATION_MESSAGE);
              }
    }//GEN-LAST:event_btnxoaspActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                         int n=JOptionPane.showConfirmDialog(this, "Bạn sẽ được chuyển qua page giới thiệu!","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (n==JOptionPane.YES_OPTION) {
                  JOptionPane.showMessageDialog(this, "Chuyển page thành công !!!!!","Chú ý",JOptionPane.INFORMATION_MESSAGE);
                    jframegioithieu x = new jframegioithieu();
                this.setVisible(false);
                x.setVisible(true);
     
        }
        else
            JOptionPane.showMessageDialog(this, "Chuyển page thất bại","Nhắc nhở",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                              int n=JOptionPane.showConfirmDialog(this, "Bạn sẽ được chuyển qua page việc làm!","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (n==JOptionPane.YES_OPTION) {
                  JOptionPane.showMessageDialog(this, "Chuyển page thành công !!!!!","Chú ý",JOptionPane.INFORMATION_MESSAGE);
                    jframeqlvieclam x = new jframeqlvieclam();
                this.setVisible(false);
                x.setVisible(true);
     
        }
        else
            JOptionPane.showMessageDialog(this, "Chuyển page thất bại","Nhắc nhở",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        panelhead.setBackground(Color.red);
        panelfoot.setBackground(Color.red);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        panelhead.setBackground(Color.ORANGE);
        panelfoot.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        panelhead.setBackground(Color.BLUE);
        panelfoot.setBackground(Color.BLUE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
        int n=JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (n==JOptionPane.YES_OPTION) {
            lichsudangnhapdao.xoataikhoanfull();
            JOptionPane.showMessageDialog(this, "Đăng xuất thành công !!!!!","Chú ý",JOptionPane.INFORMATION_MESSAGE);
            formlogin x = new formlogin();
            this.setVisible(false);
            x.setVisible(true);

        }
        else
        JOptionPane.showMessageDialog(this, "Đăng xuất  thất bại","Nhắc nhở",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
        int n=JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình !","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (n==JOptionPane.YES_OPTION) {
            lichsudangnhapdao.xoataikhoanfull();
            JOptionPane.showMessageDialog(this, "Bye bye !!!!!","Chú ý",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);

        }
        else
        JOptionPane.showMessageDialog(this, "Không thoát","Nhắc nhở",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        panelfoot.setBackground(null);
        panelhead.setBackground(null);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jframeqlaccount x = new jframeqlaccount();
        this.setVisible(false);
        x.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Tính năng đang trong quá trình nâng cấp","Thông báo",JOptionPane.INFORMATION_MESSAGE);
   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    public void demsosanpham()
    {       int count=0;
       Connection connec=null;
        PreparedStatement pre =null;
        ResultSet rs = null;
        Statement sm=null;
        sqlserverprovider provin =new sqlserverprovider();
        provin.open();
        String sql="Select count(*) from chitietsanpham";
        rs=provin.executeQuery(sql);
        
        try {
            while(rs.next())
            {
                count=rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(jframeqlthanhpham.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        txtsumsp.setText(String.valueOf(count));
        
        
    }
     public void demsonguyenlieu()
    {      
         int count=0;
       Connection connec=null;
        PreparedStatement pre =null;
        ResultSet rs = null;
        Statement sm=null;
        sqlserverprovider provin =new sqlserverprovider();
        provin.open();
        String sql="Select count(*) from nguyenlieu";
        rs=provin.executeQuery(sql);
        
        try {
            while(rs.next())
            {
                count=rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(jframeqlthanhpham.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        txtsumnl.setText(String.valueOf(count));
    }
    
    
    
    
    private void timkiemtheoten() {
                DefaultTableModel dtm=(DefaultTableModel)jtb1.getModel();
        dtm.setRowCount(0);
        
        for(nguyenlieu sh:nguyenlieudao.timkiemsachtheoten(tennl))
        {
            Object datarow[] =new Object[4];
            datarow[0] =sh.getManl();
            datarow[1] =sh.getTennl();
            datarow[2] =sh.getDangvl();
            datarow[3] =sh.getNhietdo();
           
            dtm.addRow(datarow);         
        }      
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeqlthanhpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeqlthanhpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeqlthanhpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeqlthanhpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframeqlthanhpham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddnl;
    private javax.swing.JButton btnchuyendoi;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnthemsp;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnupdatenl;
    private javax.swing.JButton btnxoanl;
    private javax.swing.JButton btnxoasp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcb;
    private javax.swing.JMenu jmenuaccout;
    private javax.swing.JTable jtb1;
    private javax.swing.JTable jtb2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JPanel panelfoot;
    private javax.swing.JPanel panelhead;
    private javax.swing.JTextField txtdang;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtnhietdo;
    private javax.swing.JTextField txtsumnl;
    private javax.swing.JTextField txtsumsp;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables

   private void Hienthi() 
   {
        
        ArrayList<nguyenlieu> ds1 = nguyenlieudao.layLiSTnguyenlieu();
        DefaultTableModel dtm1=(DefaultTableModel)jtb1.getModel();
        dtm1.setRowCount(0);
        
        for(nguyenlieu dspb:ds1)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(dspb.getManl());
            vec.add(dspb.getTennl());
            vec.add(dspb.getDangvl());
            vec.add(dspb.getNhietdo());
            dtm1.addRow(vec);
        }
        jtb1.setModel(dtm1);
        
           ArrayList<chitietsp> ds2 = chitietspdao.layLiSTctsp();
        DefaultTableModel dtm2=(DefaultTableModel)jtb2.getModel();
        dtm2.setRowCount(0);
        
        for(chitietsp dslist:ds2)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(dslist.getManl());
            vec.add(dslist.getMaloaisp());
            vec.add(dslist.getTensp());
            vec.add(dslist.getNgaysx());
            dtm2.addRow(vec);
        }
        jtb2.setModel(dtm2);
    }
 private String Laymanl() 
 {      tennl=String.valueOf(jcb.getSelectedItem());
        Connection connec=null;
        PreparedStatement pre =null;
        ResultSet rs = null;
        Statement sm=null;
        sqlserverprovider provin =new sqlserverprovider();
        provin.open();
        String sql="Select manl from nguyenlieu where tennguyenlieu='"+tennl+"'";
        rs=provin.executeQuery(sql);
    try {
        while(rs.next())
        {
            manl=rs.getString("manl");
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(jframeqlthanhpham.class.getName()).log(Level.SEVERE, null, ex);
    }
        return manl;
    }  
   
   
    private void adddatacombobox() 
    {
        Connection connec=null;
        PreparedStatement pre =null;
        ResultSet rs = null;
        Statement sm=null;
        sqlserverprovider provin =new sqlserverprovider();
        provin.open();
        String sql="Select * from nguyenlieu";
        rs=provin.executeQuery(sql);
        
        try {
            while(rs.next())
            {
                jcb.addItem(rs.getString("tennguyenlieu"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(jframeqlthanhpham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  

  
}
