/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.lichlamdao;
import dao.lichsudangnhapdao;
import dao.nguyenlieudao;
import dao.nhanviendao;
import dao.sqlserverprovider;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import pojo.lichlamviec;
import pojo.nguyenlieu;
import pojo.nhanvien;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HuuDuc
 */
public class jframeqlvieclam extends javax.swing.JFrame {
String maph="";
String tenph="";
    /**
     * Creates new form jframeqlnl
     */
    public jframeqlvieclam() {
        initComponents();
        this.setTitle("Quản lý việc làm");
        adddatacombobox();
        Hienthi();
        demsonhanvien();
        demsocalam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbcalam = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbnv = new javax.swing.JTable();
        panelfoot = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttenv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        panelhead = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtluong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsonv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsocalma = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbcalam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Ca làm", "Ngày làm"
            }
        ));
        jScrollPane1.setViewportView(jtbcalam);

        jtbnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân viên", "Tên nhân viên", "Mã phòng", "Số điện thoại", "Lương"
            }
        ));
        jtbnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbnvMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbnv);

        btnadd.setText("Thêm nhân viên");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setText("Cập nhật nhân viên");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("Xóa nhân viên");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnback.setText("Quay lại ");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelfootLayout = new javax.swing.GroupLayout(panelfoot);
        panelfoot.setLayout(panelfootLayout);
        panelfootLayout.setHorizontalGroup(
            panelfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfootLayout.createSequentialGroup()
                .addComponent(btnadd)
                .addGap(44, 44, 44)
                .addComponent(btnupdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndelete)
                .addGap(72, 72, 72)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        panelfootLayout.setVerticalGroup(
            panelfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btnreset)
                    .addComponent(btnback))
                .addContainerGap())
        );

        jLabel1.setText("Mã nhân viên :");

        jLabel2.setText("Tên nhân viên :");

        jLabel3.setText("Mã phòng ban :");

        jcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vui lòng chọn phòng ban" }));
        jcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbActionPerformed(evt);
            }
        });

        jLabel4.setText("Số điện thoại :");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/pngtree-vector-candy-icon-png-image_4159682.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/unnamed.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/37938176-exit-icon_1.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/Help_Circle_Blue.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelheadLayout = new javax.swing.GroupLayout(panelhead);
        panelhead.setLayout(panelheadLayout);
        panelheadLayout.setHorizontalGroup(
            panelheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheadLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panelheadLayout.setVerticalGroup(
            panelheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel5.setText("Lương nhân viên");

        jLabel6.setText("Số nhân viên : ");

        jLabel7.setText("Số ca làm :");

        jMenu1.setText("File");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/16225630-print-icon.jpg"))); // NOI18N
        jMenuItem4.setText("In ra");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Đổi màu Theme");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/unnamed (1).png"))); // NOI18N
        jMenuItem1.setText("Màu đỏ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/c.jpg"))); // NOI18N
        jMenuItem2.setText("Màu cam");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/1200px-Button_Icon_Blue.svg.png"))); // NOI18N
        jMenuItem3.setText("Màu xanh");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem7.setText("Mặc định");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tài khoản");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/free-settings-icon-3110-thumb.png"))); // NOI18N
        jMenuItem5.setText("Thiết lập");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jRadioButtonMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonMenuItem2.setForeground(new java.awt.Color(255, 51, 51));
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Đăng xuất");
        jRadioButtonMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/41566967-logout-button.jpg"))); // NOI18N
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Setting");

        jMenuItem6.setText("Form giữa màn hình");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Exit");

        jRadioButtonMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Exit");
        jRadioButtonMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageICON/32210569-exit-icon.jpg"))); // NOI18N
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelfoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsonv, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsocalma)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttenv)
                            .addComponent(jcb, 0, 468, Short.MAX_VALUE)
                            .addComponent(txtsdt)
                            .addComponent(txtmanv, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtluong)))))
            .addComponent(panelhead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelhead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txttenv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtsonv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtsocalma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelfoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        
             int row=this.jtbnv.getSelectedRow();
        
          if (jtbnv.getSelectedRow()==-1) 
          {
            JOptionPane.showMessageDialog(this, "Hãy chọn dòng cần xóa");
            return;
          }
            int xoa = JOptionPane.showConfirmDialog(this,
                    "bạn có muốn xóa không","Thông Báo", JOptionPane.YES_NO_OPTION,JOptionPane.YES_OPTION);
              if (xoa==JOptionPane.YES_OPTION) 
            {
                String ma=(String.valueOf(jtbnv.getValueAt(row, 0))) ;
               nhanvien sh = new nhanvien();
                 sh.setManv(ma);
                 nhanviendao.xoanv(sh);
                  JOptionPane.showMessageDialog(this,"xóa thành công","thông báo",JOptionPane.WARNING_MESSAGE);
//                   demsonguyenlieu();
demsonhanvien();
                  Hienthi();
            }
              else
              {
                   JOptionPane.showMessageDialog(this,"xóa thất bại","thông báo",JOptionPane.INFORMATION_MESSAGE);
              }
    }//GEN-LAST:event_btndeleteActionPerformed

    private boolean checktrungmanv()
{       int ketqua=0;boolean kq=false;
        String maofnl=txtmanv.getText();
        ResultSet rs = null;
        sqlserverprovider provin =new sqlserverprovider();
        provin.open();
        String sql="Select count(*) from nhanvien where manv='"+maofnl+"'";
        rs=provin.executeQuery(sql);
    try {
        while(rs.next())
        {
            ketqua=rs.getInt(1);
        }
        if (ketqua>0) {
            kq=true;
        }
    } catch (SQLException ex) {
        Logger.getLogger(jframeqlthanhpham.class.getName()).log(Level.SEVERE, null, ex);
    }
    provin.close();
    return kq;
}
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
              nhanvien sh=new nhanvien();
        String mapb=manph();
    
        if(txtmanv.getText().isEmpty()==true || txttenv.getText().isEmpty()==true||txtsdt.getText().isEmpty()==true || txtluong.getText().isEmpty()==true||jcb.getSelectedIndex()==0)
        {
            
//            redtxt(error);
             JOptionPane.showMessageDialog(this,"Không được để trống","Nhắc nhở",JOptionPane.WARNING_MESSAGE);
        }
        else if(checktrungmanv()==true)
        {
            JOptionPane.showMessageDialog(this, "Đã tồn tại mã nhân viên ,vui lòng kiểm tra lại","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            sh.setManv(txtmanv.getText());
            sh.setTennv(txttenv.getText());
            sh.setMaph(mapb);
            sh.setSdt(txtsdt.getText());
            sh.setLuong(Float.valueOf(txtluong.getText()) );
            nhanviendao.themnv(sh);
//            redtxt(false);
            Hienthi();
//            demsonguyenlieu();
demsonhanvien();
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công ! ","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnaddActionPerformed
    private String manph()
    {   String maphong="";
         tenph=String.valueOf(jcb.getSelectedItem())  ;
          ResultSet rs = null;
          sqlserverprovider provin =new sqlserverprovider();
        provin.open();
        String sql= String.format("Select * from phongban where tenph=N'%s'",tenph);
        rs=provin.executeQuery(sql);
        try {
            while(rs.next())
            {
                 maphong=rs.getString("maph");
            }
        } catch (SQLException ex) {
            Logger.getLogger(jframeqlvieclam.class.getName()).log(Level.SEVERE, null, ex);
        }
        return maphong;
    }
    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        jframemain  x = new jframemain();
        this.setVisible(false);
        x.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtmanv.setText("");
        txttenv.setText("");
        txtsdt.setText("");
        txtluong.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        int row = jtbnv.getSelectedRow();
       String sdt=txtsdt.getText();
       float Luong=Float.valueOf(txtluong.getText()) ;
       String ma = txtmanv.getText();
       String ten =txttenv.getText();
       String mapb = manph() ;
        if(row==-1)
       {
           JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần cập nhật","Thông báo",JOptionPane.WARNING_MESSAGE);
       }
        else
        {
            if(jcb.getSelectedIndex()==-1)
            {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn lại hoặc chọn mới phòng ban !","Thông báo",JOptionPane.WARNING_MESSAGE);
            }
            else if(checktrungmanv()==false)
            {
                JOptionPane.showMessageDialog(this, "Mã nhân viên không tồn tại vui lòng kiểm tra lại","Thông báo",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                nhanvien sh=new nhanvien();   
                 sh.setManv(txtmanv.getText());
            sh.setTennv(txttenv.getText());
            sh.setMaph(mapb);
            sh.setSdt(txtsdt.getText());
            sh.setLuong(Float.valueOf(txtluong.getText()) );
                nhanviendao.capnhatnv(sh);
                Hienthi();
              JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công ! ","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbActionPerformed
        // TODO add your handling code here:
        String tenph=String.valueOf(jcb.getSelectedItem());
        ResultSet rs = null;
          sqlserverprovider provin =new sqlserverprovider();
        provin.open();
        String sql="Select * from phongban where tenph=N'"+tenph+"'";
        rs=provin.executeQuery(sql);
        try {
            while(rs.next())
            {
                maph=rs.getString("maph");
            }
        } catch (SQLException ex) {
            Logger.getLogger(jframeqlvieclam.class.getName()).log(Level.SEVERE, null, ex);
        }
        
          if(jcb.getSelectedIndex()==0)
        {
            Hienthi();
        }
        else
          {
                    ArrayList<nhanvien> ds1 = nhanviendao.layLiSTnhanvien();
                 DefaultTableModel dtm1=(DefaultTableModel)jtbnv.getModel();
                 dtm1.setRowCount(0);

                 for(nhanvien dspb:nhanviendao.timkiemnvtheoten(maph))
                 {
                     Vector<Object> vec = new Vector<Object>();
                     vec.add(dspb.getManv());
                     vec.add(dspb.getTennv());
                     vec.add(dspb.getMaph());
                     vec.add(dspb.getSdt());
                     vec.add(dspb.getLuong());
                     dtm1.addRow(vec);
                 }
                 jtbnv.setModel(dtm1);
              }
    }//GEN-LAST:event_jcbActionPerformed

    private void jtbnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbnvMouseClicked
        // TODO add your handling code here:
        int row=jtbnv.getSelectedRow();
      
//        maph=String.valueOf(jtbnv.getValueAt(row, 3)) ;
//        
//         ResultSet rs = null;
//          sqlserverprovider provin =new sqlserverprovider();
//        provin.open();
//        String sql= String.format("Select * from phongban where maph='%s'",maph);
//        rs=provin.executeQuery(sql);
//        try {
//            while(rs.next())
//            {
//                tenph=rs.getString("tenph");
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(jframeqlvieclam.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        jcb.setSelectedItem(tenph);
        
          txtmanv.setText(String.valueOf(jtbnv.getValueAt(row, 0)));
        txttenv.setText(String.valueOf(jtbnv.getValueAt(row, 1)));
        txtsdt.setText(String.valueOf(jtbnv.getValueAt(row, 3)));
        txtluong.setText(String.valueOf(jtbnv.getValueAt(row, 4)));
    }//GEN-LAST:event_jtbnvMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                   int n=JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình !","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (n==JOptionPane.YES_OPTION) {
            lichsudangnhapdao.xoataikhoanfull();
                  JOptionPane.showMessageDialog(this, "Bye bye !!!!!","Chú ý",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
     
        }
        else
            JOptionPane.showMessageDialog(this, "Không thoát","Nhắc nhở",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
                             int n=JOptionPane.showConfirmDialog(this, "Bạn sẽ được chuyển qua page giới thiệu!","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (n==JOptionPane.YES_OPTION) {
                  JOptionPane.showMessageDialog(this, "Chuyển page thành công !!!!!","Chú ý",JOptionPane.INFORMATION_MESSAGE);
                    jframegioithieu x = new jframegioithieu();
                this.setVisible(false);
                x.setVisible(true);
     
        }
        else
            JOptionPane.showMessageDialog(this, "Chuyển page thất bại","Nhắc nhở",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                                     int n=JOptionPane.showConfirmDialog(this, "Bạn sẽ được chuyển qua page quản lý thành phẩm!","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (n==JOptionPane.YES_OPTION) {
                  JOptionPane.showMessageDialog(this, "Chuyển page thành công !!!!!","Chú ý",JOptionPane.INFORMATION_MESSAGE);
                    jframeqlthanhpham x = new jframeqlthanhpham();
                this.setVisible(false);
                x.setVisible(true);
     
        }
        else
            JOptionPane.showMessageDialog(this, "Chuyển page thất bại","Nhắc nhở",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        panelhead.setBackground(Color.red);
        panelfoot.setBackground(Color.red);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
        int n=JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (n==JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Đăng xuất thành công !!!!!","Chú ý",JOptionPane.INFORMATION_MESSAGE);
            formlogin x = new formlogin();
            this.setVisible(false);
            x.setVisible(true);

        }
        else
        JOptionPane.showMessageDialog(this, "Đăng xuất  thất bại","Nhắc nhở",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
        int n=JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình !","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (n==JOptionPane.YES_OPTION) {
            lichsudangnhapdao.xoataikhoanfull();
            JOptionPane.showMessageDialog(this, "Bye bye !!!!!","Chú ý",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);

        }
        else
        JOptionPane.showMessageDialog(this, "Không thoát","Nhắc nhở",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        panelhead.setBackground(Color.ORANGE);
        panelfoot.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        panelhead.setBackground(Color.BLUE);
         panelfoot.setBackground(Color.BLUE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        panelfoot.setBackground(null);
        panelhead.setBackground(null);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jframeqlaccount x = new jframeqlaccount();
        this.setVisible(false);
        x.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Tính năng đang trong quá trình nâng cấp","Thông báo",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeqlvieclam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeqlvieclam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeqlvieclam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeqlvieclam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframeqlvieclam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcb;
    private javax.swing.JTable jtbcalam;
    private javax.swing.JTable jtbnv;
    private javax.swing.JPanel panelfoot;
    private javax.swing.JPanel panelhead;
    private javax.swing.JTextField txtluong;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtsocalma;
    private javax.swing.JTextField txtsonv;
    private javax.swing.JTextField txttenv;
    // End of variables declaration//GEN-END:variables

    private void Hienthi() 
    {
          ArrayList<nhanvien> ds1 = nhanviendao.layLiSTnhanvien();
        DefaultTableModel dtm1=(DefaultTableModel)jtbnv.getModel();
        dtm1.setRowCount(0);
        
        for(nhanvien dspb:ds1)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(dspb.getManv());
            vec.add(dspb.getTennv());
            vec.add(dspb.getMaph());
            vec.add(dspb.getSdt());
            vec.add(dspb.getLuong());
            dtm1.addRow(vec);
        }
        jtbnv.setModel(dtm1);
        
        
          ArrayList<lichlamviec> ds2 = lichlamdao.layLiSTlichlam();
        DefaultTableModel dtm2=(DefaultTableModel)jtbcalam.getModel();
        dtm2.setRowCount(0);
        
        for(lichlamviec dspb1:ds2)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(dspb1.getManv());
            vec.add(dspb1.getCalam());
            vec.add(dspb1.getNgaylam());
            dtm2.addRow(vec);
        }
        jtbcalam.setModel(dtm2);
    }

    private void adddatacombobox() {
        ResultSet rs = null;
        sqlserverprovider provin =new sqlserverprovider();
        provin.open();
        String sql="Select * from phongban";
        rs=provin.executeQuery(sql);
        
        try {
            while(rs.next())
            {
                jcb.addItem(rs.getString("tenph"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(jframeqlthanhpham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void demsonhanvien() {
         int count=0;
    
        ResultSet rs = null;
        sqlserverprovider provin =new sqlserverprovider();
        provin.open();
        String sql="Select count(*) from nhanvien";
        rs=provin.executeQuery(sql);
        
        try {
            while(rs.next())
            {
                count=rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(jframeqlthanhpham.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        txtsonv.setText(String.valueOf(count));

    }

    private void demsocalam() {
         int count=0;
        ResultSet rs = null;
        sqlserverprovider provin =new sqlserverprovider();
        provin.open();
        String sql="Select count(*) from lichlamviec";
        rs=provin.executeQuery(sql);
        
        try {
            while(rs.next())
            {
                count=rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(jframeqlthanhpham.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        txtsocalma.setText(String.valueOf(count));

    }
}
